# Generated by Django 4.0.4 on 2022-05-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_and_review", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="content",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="caption",
        ),
    ]
