# Generated by Django 4.0.4 on 2022-05-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ticket_and_review",
            "0002_rename_content_blog_description_remove_photo_caption",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                help_text=None, upload_to="", verbose_name="image"
            ),
        ),
    ]
