# Generated by Django 4.0.4 on 2022-05-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_and_review', '0007_photo_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.CharField(default='rffe', max_length=5000, verbose_name='contenu'),
            preserve_default=False,
        ),
    ]
