# Generated by Django 4.0.4 on 2022-05-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_and_review", "0008_blog_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="content",
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(max_length=5000, verbose_name="contenu"),
        ),
    ]
