# Generated by Django 4.0.4 on 2022-05-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ticket_and_review",
            "0009_remove_blog_content_alter_blog_description",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="caption",
        ),
    ]
