# Generated by Django 4.0.4 on 2022-05-16 17:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket_and_review', '0011_alter_blog_description_alter_blog_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Ticket',
        ),
    ]
