# Generated by Django 4.0.4 on 2022-05-17 08:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ticket_and_review", "0012_rename_blog_ticket"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Photo",
            new_name="Image",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="photo",
            new_name="image",
        ),
    ]
