# Generated by Django 4.0.4 on 2022-05-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_and_review", "0031_alter_review_ticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="ticket",
        ),
    ]
