# Generated by Django 4.0.4 on 2022-06-07 11:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_and_review", "0039_alter_autoreview_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoreview",
            name="body",
            field=models.TextField(blank=True, max_length=8192),
        ),
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(blank=True, max_length=8192),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                max_length=1024,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ticket_and_review.ticket",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.TextField(
                blank=True, max_length=2048, verbose_name="Description"
            ),
        ),
    ]
