# Generated by Django 4.0.4 on 2022-06-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_and_review", "0048_alter_autoreview_ticket"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AutoReview",
        ),
    ]
